# Generated by Django 3.2.4 on 2021-09-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('05', 'Uttam Nagar'), ('06', 'East Azad Nagar'), ('07', 'Pitampura'), ('08', 'Kalka Ji'), ('09', 'Badarpur'), ('10', 'Dilshad Garden')], max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('counselor', 'Counselor'), ('centerhead', 'Centerhead'), ('faculty', 'Faculty')], max_length=20)),
            ],
        ),
    ]
