# Generated by Django 3.2.4 on 2021-09-28 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('05', 'Uttam Nagar'), ('06', 'East Azad Nagar'), ('07', 'Pitampura'), ('08', 'Kalka Ji'), ('09', 'Badarpur'), ('10', 'Dilshad Garden')], max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('counselor', 'Counselor'), ('centerhead', 'Centerhead'), ('faculty', 'Faculty')], max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
