# Generated by Django 3.2.7 on 2021-11-19 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211118_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='batch1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='secondarybatch', to='home.batch'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.course'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.module'),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='primarybatch', to='home.batch'),
        ),
    ]
